exclude_patterns:
 - docs/*
 - tests/*
 - src/sys/external/*
 - phpunit.php
 - vendor/*
rules:
 php.use_global_variable_or_function:
  enabled: false
 git.user_specific_ignored_file:
  enabled: false
 php.neglected_tests:
  enabled: false
# the above rule should remove the false positive. All files are loaded via the phpunit.php bootstrap file.
